In [1]:
#Numpy Operation
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()
data=iris.data
feature_names=iris.feature_names

In [3]:
#Basic Operation on Arrays
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)
print('First array:')
print(arr1)
print('\nSecond array:')
arr2 = np.array([12, 12])
print(arr2)
print('\nAdding the two arrays:')
print(np.add(arr1, arr2))
print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [4]:
#Mean Calculation
mean=np.mean(data,axis=0)
print("Mean of Each feature is :- ")
for name, mean in zip(feature_names, mean):
    print(f"{name}: {mean:.3f}")

Mean of Each feature is :- 
sepal length (cm): 5.843
sepal width (cm): 3.057
petal length (cm): 3.758
petal width (cm): 1.199


In [5]:
#Median Calculation
median=np.median(data,axis=0)
print("Median of Each feature is :- ")
for name, median in zip(feature_names, median):
    print(f"{name}: {median:.3f}")

Median of Each feature is :- 
sepal length (cm): 5.800
sepal width (cm): 3.000
petal length (cm): 4.350
petal width (cm): 1.300


In [6]:
#Standard Deviation
std=np.std(data,axis=0)
print("Standard Deviation of Each feature is :- ")
for name, std in zip(feature_names, std):
    print(f"{name}: {std:.3f}")

Standard Deviation of Each feature is :- 
sepal length (cm): 0.825
sepal width (cm): 0.434
petal length (cm): 1.759
petal width (cm): 0.760


In [7]:
#Sum
sum=np.sum(data,axis=0)
print("Sum of Each feature is :- ")
for name, sum in zip(feature_names, sum):
    print(f"{name}: {sum:.3f}")

Sum of Each feature is :- 
sepal length (cm): 876.500
sepal width (cm): 458.600
petal length (cm): 563.700
petal width (cm): 179.900


In [8]:
#Highest Total Measurement
total_measurement=np.sum(data,axis=0)
max_index=np.argmax(total_measurement)
print(f"\nSample with the Highest Total Measurement:")
print(f"Index: {max_index}, Total Measurement: {total_measurement[max_index]:.1f}")


Sample with the Highest Total Measurement:
Index: 0, Total Measurement: 876.5


In [9]:
#Sorting Data by Sepal Length
sorted_data = data[np.argsort(data[:, 0])]  # Sort by the first column (Sepal Length)
print("\nSorted Dataset by Sepal Length (First Few Rows):")
print(sorted_data[:10])


Sorted Dataset by Sepal Length (First Few Rows):
[[4.3 3.  1.1 0.1]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [10]:
#Variance Calculation
variance=np.var(data,axis=0)
print("Variance of Each feature is :- ")
for name , var in zip(feature_names,variance):
  print(f"{name}: {var:.3f}")

Variance of Each feature is :- 
sepal length (cm): 0.681
sepal width (cm): 0.189
petal length (cm): 3.096
petal width (cm): 0.577


In [21]:
#Pandas Operation
import pandas as pd
#Basic Operation
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
df=pd.DataFrame(data)
print(df)
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df.describe()

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [44]:
#Sum Most Used Operation
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
dff=pd.DataFrame(dict)
print(dff.isnull())
print(dff.fillna(dff['First Score'].mean()))
df[25:50]

   First Score  Second Score  Third Score  Fourth Score
0        False         False        False          True
1        False          True        False          True
2         True         False        False          True
3        False         False        False         False
   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52          95.0
1         90.0          95.0           40          95.0
2         95.0          45.0           80          95.0
3         95.0          56.0           98          65.0


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
25                5.0               3.0                1.6               0.2   
26                5.0               3.4                1.6               0.4   
27                5.2               3.5                1.5               0.2   
28                5.2               3.4                1.4               0.2   
29                4.7               3.2                1.6               0.2   
30                4.8               3.1                1.6               0.2   
31                5.4               3.4                1.5               0.4   
32                5.2               4.1                1.5               0.1   
33                5.5               4.2                1.4               0.2   
34                4.9               3.1                1.5               0.2   
35                5.0               3.2                1.2               0.2   
36                5.5               3.5                1.3               0.2   
37                4.9               3.6                1.4               0.1   
38                4.4               3.0                1.3               0.2   
39                5.1               3.4                1.5               0.2   
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   

   species  total_measurement  
25  setosa                9.8  
26  setosa               10.4  
27  setosa               10.4  
28  setosa               10.2  
29  setosa                9.7  
30  setosa                9.7  
31  setosa               10.7  
32  setosa               10.9  
33  setosa               11.3  
34  setosa                9.7  
35  setosa                9.6  
36  setosa               10.5  
37  setosa               10.0  
38  setosa                8.9  
39  setosa               10.2  
40  setosa               10.1  
41  setosa                8.4  
42  setosa                9.1  
43  setosa               10.7  
44  setosa               11.2  
45  setosa                9.5  
46  setosa               10.7  
47  setosa                9.4  
48  setosa               10.7  
49  setosa                9.9

In [23]:
#Grouping the data and Calculating the Mean
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
print("Mean of Each Feature Grouped by Species:")
print(df.groupby('species').mean())


Mean of Each Feature Grouped by Species:
            sepal length (cm)  sepal width (cm)  petal length (cm)  \
species                                                              
setosa                  5.006             3.428              1.462   
versicolor              5.936             2.770              4.260   
virginica               6.588             2.974              5.552   

            petal width (cm)  
species                       
setosa                 0.246  
versicolor             1.326  
virginica              2.026  


<ipython-input-23-ae38b4750f55>:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('species').mean())


In [24]:
#Counting the Number of Sample for Each Species
print("Count of Samples for Each Species:")
print(df['species'].value_counts())


Count of Samples for Each Species:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


In [25]:
#Adding a New Column for Total Measurement
df['total_measurement'] = df.iloc[:, :-1].sum(axis=1)
print("DataFrame with Total Measurement Column :")
print(df.head())


DataFrame with Total Measurement Column (First Few Rows):
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  total_measurement  
0  setosa               10.2  
1  setosa                9.5  
2  setosa                9.4  
3  setosa                9.4  
4  setosa               10.2  


In [26]:
#Sorting the Dataset by sepal Width
sorted_df=df.sort_values(by='sepal width (cm)', ascending=False)
print("Dataset Sorted by Sepal Length :")
print(sorted_df.head())

Dataset Sorted by Sepal Length :
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
15                5.7               4.4                1.5               0.4   
33                5.5               4.2                1.4               0.2   
32                5.2               4.1                1.5               0.1   
14                5.8               4.0                1.2               0.2   
16                5.4               3.9                1.3               0.4   

   species  total_measurement  
15  setosa               12.0  
33  setosa               11.3  
32  setosa               10.9  
14  setosa               11.2  
16  setosa               11.0  


In [27]:
#Filtering Row where petal length greater than 1.5
filtered_df = df[df['petal length (cm)'] > 1.5]
print("Filtered Rows Where Petal Width > 1.5:")
print(filtered_df)

Filtered Rows Where Petal Width > 1.5:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
5                  5.4               3.9                1.7               0.4   
11                 4.8               3.4                1.6               0.2   
18                 5.7               3.8                1.7               0.3   
20                 5.4               3.4                1.7               0.2   
23                 5.1               3.3                1.7               0.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1           